### PR TITLE
Oneezy master

### PR DESCRIPTION
**Pull request by caranicas**
### Status
**IN DEVELOPMENT** :yellow_heart:
 
### Description

Reviewing the PR for creating an internal folder.

### Issues Addressed

 - [ ] #10  :sparkles: 

### Related PRs

branch | PR     | Status
------ | ------ | -----
oneezy-master | #28 | :construction:

#### Sign off

- [x] code reviewed by @
- [x] tested by @
- [ ] good to go! :squirrel:

### CODE REVIEW

**Comment by caranicas** [comment]
@oneezy I took a look, you were right about the refactor with `destinationRoot` I found this info about working with the [file system](http://yeoman.io/authoring/file-system.html) in Yeoman. 

I also cleaned up some of the white space you added as it didn't really fit with our (completely unpublished) style guide.

Take a look and let me know what you think. I'll merge this into your PR and then merge that into master. 💯

**Comment by caranicas** [comment]
ping @oneezy

**Comment by oneezy** [comment]
yo @caranicas , sorry man. Got caught up w/ a bunch of stuff. I'm about to merge

**Comment by caranicas** [comment]
all good. it looked good to me, I was just hoping to get some second eyes on it, make sure it was still doing everything you were expecting.

**Comment by oneezy** [comment]
Sure thing, I'll be able to test it thoroughly a bit later today

**Pull request merged**
